name: SophiBackpacks
version: "1.21.10-1.0"
main: io.github.tootertutor.SophiBackpacks.SophiBackpacksPlugin
api-version: "1.21"

commands:
  backpack:
    description: Main command for SophiBackpacks
    usage: /sophi <subcommand>
    aliases: [backpack]
    permission: sophibackpacks.command
permissions:
  sophibackpacks.command:
    default: op
  sophibackpacks.reload:
    default: op
  sophibackpacks.admin:
    default: op
