name: ModularPacks
version: "1.21.10-2.3.3"
main: io.github.tootertutor.ModularPacks.ModularPacksPlugin
api-version: "1.21"

commands:
  backpack:
    description: Main command for ModularPacks
    usage: /mp <subcommand>
    aliases: [backpack]
    permission: modularpacks.command
permissions:
  modularpacks.command:
    default: true
  modularpacks.reload:
    default: op
  modularpacks.admin:
    default: op
  modularpacks.recipe:
    default: true

  modularpacks.place:
    default: true
  modularpacks.pickup:
    default: true
  modularpacks.open:
    default: true
