name: ModularPacks
version: "1.21.10-1.0"
main: io.github.tootertutor.ModularPacks.ModularPacksPlugin
api-version: "1.21"

commands:
  backpack:
    description: Main command for ModularPacks
    usage: /mp <subcommand>
    aliases: [backpack]
    permission: modularpacks.command
permissions:
  modularpacks.command:
    default: op
  modularpacks.reload:
    default: op
  modularpacks.admin:
    default: op
