package io.github.tootertutor.ModularPacks.item;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;

import io.github.tootertutor.ModularPacks.ModularPacksPlugin;
import io.github.tootertutor.ModularPacks.data.BackpackData;
import io.github.tootertutor.ModularPacks.data.ItemStackCodec;

/**
 * Generates Custom Model Data strings based on installed modules in a backpack.
 * 
 * This allows resource packs to detect which module is installed in each slot
 * and render additional models on top of the base backpack model.
 * 
 * Format: `modularpacks.slot.<index>:<moduleType>`
 * Example: If an "Everlasting" module is installed in slot 3, the string would
 * be: `modularpacks.slot.3:everlasting`
 */
public final class ModuleModelDataGenerator {

    private ModuleModelDataGenerator() {
    }

    /**
     * Generate Custom Model Data strings for all installed modules in a backpack.
     *
     * Format: "modularpacks.slot.<index>:<moduleType>" for occupied slots,
     * "modularpacks.slot.<index>:" for empty slots.
     * This explicitly defines both the slot number and what module (if any) is in
     * it.
     *
     * @param plugin       The plugin instance
     * @param backpackData The backpack data containing module information
     * @return List of exactly 5 CMD strings, indexed by slot position
     */
    public static List<String> generateModuleModelDataStrings(ModularPacksPlugin plugin, BackpackData backpackData) {
        // Initialize array with 5 strings, one per slot
        List<String> moduleStrings = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            moduleStrings.add("modularpacks.slot." + i + ":");
        }

        if (backpackData != null) {
            Keys keys = plugin.keys();
            Map<Integer, UUID> installedModules = backpackData.installedModules();

            // Iterate through slots 0-4 and set each module's string
            for (int slot = 0; slot < 5; slot++) {
                UUID moduleId = installedModules.get(slot);
                if (moduleId == null) {
                    continue;
                }

                ItemStack moduleSnapshot = resolveModuleSnapshot(backpackData, moduleId);
                if (moduleSnapshot == null || !moduleSnapshot.hasItemMeta()) {
                    continue;
                }

                ItemMeta moduleMeta = moduleSnapshot.getItemMeta();
                if (moduleMeta == null) {
                    continue;
                }

                String moduleType = moduleMeta.getPersistentDataContainer().get(keys.MODULE_TYPE,
                        PersistentDataType.STRING);
                if (moduleType == null || moduleType.isBlank()) {
                    continue;
                }

                var def = plugin.cfg().findUpgrade(moduleType);
                if (def == null || !def.enabled()) {
                    continue;
                }

                if (def.toggleable()) {
                    Byte enabledByte = moduleMeta.getPersistentDataContainer().get(keys.MODULE_ENABLED,
                            PersistentDataType.BYTE);
                    if (enabledByte != null && enabledByte == 0) {
                        continue;
                    }
                }

                // Set the string with module type explicitly tied to its slot
                moduleStrings.set(slot, "modularpacks.slot." + slot + ":" + moduleType.toLowerCase(Locale.ROOT));
            }
        }

        return moduleStrings;
    }

    /**
     * Generate a fallback integer encoding of the slot-to-module configuration.
     *
     * Uses a simple marker system where each slot gets a value 1 if occupied, 0 if
     * empty.
     * This is a fallback for when string matching isn't supported and should not be
     * used to determine rendering order - the slot strings should be authoritative.
     *
     * Formula: slot0 + (slot1 × 2) + (slot2 × 4) + (slot3 × 8) + (slot4 × 16)
     *
     * @param moduleStrings The strings generated by generateModuleModelDataStrings
     * @return An integer encoding of the module configuration
     */
    public static int generateModuleEncodingInteger(List<String> moduleStrings) {
        int encoding = 0;
        int multiplier = 1;

        for (int slot = 0; slot < 5 && slot < moduleStrings.size(); slot++) {
            String slotString = moduleStrings.get(slot);
            int slotValue = 0;

            // Each slot is either empty (ends with ":") or occupied (has module type after
            // ":")
            if (slotString.contains(":") && !slotString.endsWith(":")) {
                slotValue = 1; // Slot has a module
            }

            encoding += slotValue * multiplier;
            multiplier *= 2; // Use binary encoding instead of base-15
        }

        return encoding;
    }

    /**
     * Resolve a module's ItemStack snapshot from the backpack data.
     * 
     * @param backpackData The backpack data
     * @param moduleId     The module UUID
     * @return The module ItemStack snapshot, or null if not found
     */
    private static ItemStack resolveModuleSnapshot(BackpackData backpackData, UUID moduleId) {
        if (backpackData == null || moduleId == null) {
            return null;
        }

        byte[] snapshotBytes = backpackData.installedSnapshots().get(moduleId);
        if (snapshotBytes == null || snapshotBytes.length == 0) {
            return null;
        }

        try {
            ItemStack[] items = ItemStackCodec.fromBytes(snapshotBytes);
            if (items.length == 0) {
                return null;
            }
            return items[0];
        } catch (Exception e) {
            return null;
        }
    }
}
